name: 'Terraform'

on: [push, pull_request]

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Terraform init
    - name: Terraform Init
      id: init
      run: terraform init 
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color