name: 'Terraform'

on: [push, pull_request]

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run terraform fmt check
      run: terraform fmt -check -diff -recursive ./terraform

    # Terraform init
    - name: Terraform Init
      id: init
      run: terraform init 
    
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color

    - name: Post Plan to GitHub PR
      uses: mshick/add-pr-comment@v1
      with:
        allow-repeats: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          ## Terraform plan
          ```
          ${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}
          ```            